### ISSUE TITLE
firefly3 python module

### ISSUE THREAD

**Issue by rylos** [Royalphax/credit-agricole-importer#1]
Hi, i've firefly3 running in dockers. I've tried your script but it can't find the firefly3 python module.
`from firefly3 import Firefly3Client, Firefly3Transactions`
where are you running this script from or where can I download this module? It's not in the `requirements.txt`

**Ok problem is not the module but syntax error on firefly3.py line 162, there is an empty IF**

Thank you in advance

**Comment by Royalphax** [comment]
Hello @rylos 
I'm sorry for this mistake, now it has been fixed.
You should use in priority code from [releases](https://github.com/Royalphax/credit-agricole-importer/releases/tag/v0.1.0) which has been tested.
I'm working hard to improve the project week by week, so thanks a lot for your comments 👍🏻

**Comment by rylos** [comment]
Ok thank you.
