### ISSUE TITLE
Not compatible with newer versions of creditagricole-particuliers authenticator

### ISSUE THREAD

**Issue by charchess** [Royalphax/credit-agricole-importer#3]
Hi, 

you'll need to update your code to reflect the newer versions of the library creditagricole-particuliers, the third argument is not region anymore but department.

nice work all the same

Charchess

**Comment by coolcow** [comment]
Please try my [pull-request](https://github.com/Royalphax/credit-agricole-importer/pull/10). It works now for me and should for everyone else too.

**Comment by Royalphax** [comment]
Fixed in next release.
