### ISSUE TITLE
suggestion for transfer detection improvement

### ISSUE THREAD

**Issue by coolcow** [Royalphax/credit-agricole-importer#6]
The detection of transfers is a) not working for some reason (at least not for me) and b) not reliable enough (by looking on the code).

How it's done currently:
```
 # Loop through all transaction packages
  # Count detected transfers for later test
  # Loop through dates of outgoing transfers of the above transaction package
   # Loop through outgoing transfers for the above date
    # Get the amount
    # Now loop through other transaction packages
     # If the above transaction package is the same than the first one, skip it
     # Loop through dates of incoming transfers
      # If the incoming transfer date is the same than our outgoing transfer date, check amounts
       # Loop through incoming transfers
        # Get the amount
        # If incoming transfer amount is the same than outgoing transfer amount,
        # it means that we found a corresponding incoming transfer for our outgoing transfer
         # We clarify the transfer payload (who's the source and destination)
         # We rename the transaction
         # We save the payload to push it later
```
I don't think that the date and amount of the operation is sufficient for detecting a transfer. The risk that another operation gets detected as transfer by mistake is to high IMHO.

I analyzed the data of the operations for my account, and observed the following; Transfers have always:
* the `familleTypeOperation: 6` ("VIREMENT EMIS") for the outgoing and `familleTypeOperation: 7` ("VIREMENT EN VOTRE FAVEUR") for the ingoing part.
* a `fitid` that differs by exactly 1 (the smaller one is the outgoing, and the bigger one is the ingoing operation)

I would not take into account the date for the transfer detection, since the fitid is a pretty precise indicator that the 2 operations are related to eachother.

**Comment by coolcow** [comment]
I am not very familiar with python, but if i find the time and energy for it, i might try to implement the idea by myself and make a pull request for it.

**Comment by coolcow** [comment]
I now know why it isn't working for me:

```
transfer-source-transaction-name = WEB LASTNAME FIRSTNAME
transfer-destination-transaction-name = DE LASTNAME FIRSTNAME
```

This only works if the "LASTNAME FIRSTNAME" is not too long, and also if there was no `referenceClient` set for the transfer (since this gets concatenated into `libelleOperation`). 

One reason more to change the transfer detection. I am already working on it...

**Comment by coolcow** [comment]
I finished a working and stable solution over the weekend, but it involves some non-trivial refactoring, which is relying on the changes i made in my other pull requests. That's why i wait for them to be merged before proposing the new changes. (@Royalphax)

Otherwise i will simply publish it on my fork, but i would prefer to contribute to this project instead of working against it.

**Comment by Royalphax** [comment]
Hello @coolcow,
Thanks a lot for your deep dive into the CreditAgricole's data for each transfers.
Now, when you mentioned the `familleTypeOperation` and the `fitid`, it rang the same bell as you.
I've merged all your pull requests. Now, I'm eagerly awaiting to review your code for a smoother integration of the transfer detection.

PS: Yes, the initial implementation of the transfer detection was a bit... "presumptuous". I'm relieved you succeeded in implementing it using fitid; otherwise, I might have attempted it myself. Once again, thank you for your work, which will benefit all of us!

**Comment by coolcow** [comment]
I made the pull request. Didn't have the time and energy to make single commits for each change, so sorry about the mess. I hope you can make some sense of it.

I close here, since the discussion can continue on the pull request itself if needed.
