### ISSUE TITLE
Personal access token length is not always 980

### ISSUE THREAD

**Issue by M-Gregoire** [Royalphax/credit-agricole-importer#9]
The importer checks that the PAT used to access Firefly is the same length as `PERSONAL_TOKEN_DEFAULT` but tokens generated from my instance are longer than `980` characters (933 or 944 characters in my case).

Removing ` len(self.token) != len(PERSONAL_TOKEN_DEFAULT) ` fixes the problem.

Maybe the check should be different (Or removed altogether?).

I'm happy to raise a PR if you want.

**Comment by Royalphax** [comment]
I was starting to fix this myself but I saw your last sentence.

Don't hesitate to suggest PRs, I think that if everyone contributes, it will make the application even more robust and full of features, so I'll let you suggest a PR (even if it's a small fix!).

After your PR, I will make a full review of the project as I recently merged several PRs and I would like to ensure that there is no security issues.
